In [25]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [26]:
house_prices = pd.read_csv("data.csv")
house_prices.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [27]:
house_prices.drop(columns=["date", "street", "city", "statezip", "country"], inplace=True)
house_prices.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0     0          3        1340              0      1955          2005  
1     4          5        3370            280      1921             0  
2     0          4        1930              0      1966             0  
3     0          4        1000           1000      1963             0  
4     0          4        1140            800      1976          1992

In [28]:
X = house_prices.drop(columns="price")
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0       3.0       1.50         1340      7912     1.5           0     0   
1       5.0       2.50         3650      9050     2.0           0     4   
2       3.0       2.00         1930     11947     1.0           0     0   
3       3.0       2.25         2000      8030     1.0           0     0   
4       4.0       2.50         1940     10500     1.0           0     0   

   condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0          3        1340              0      1955          2005  
1          5        3370            280      1921             0  
2          4        1930              0      1966             0  
3          4        1000           1000      1963             0  
4          4        1140            800      1976          1992

In [29]:
y = house_prices.loc[:, "price"]
y.head()

0     313000.0
1    2384000.0
2     342000.0
3     420000.0
4     550000.0
Name: price, dtype: float64

In [55]:
price_prediction = tf.keras.models.Sequential([
    tf.keras.Input(shape=12, name="Input layer"),
    tf.keras.layers.Dense(units=6, activation=tf.keras.activations.linear, name="layer2"),
    tf.keras.layers.Dense(units=24, activation=tf.keras.activations.linear, name="layer3"),
    tf.keras.layers.Dense(units=1, name="Output")
])

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, shuffle=True, random_state=9)

In [56]:
price_prediction.compile(loss=tf.keras.losses.MeanAbsoluteError(), optimizer="adam")
price_prediction.fit(X_train, y_train)

115/115 [==============================] - 1s 2ms/step - loss: 543201.0625


In [33]:
y_test.shape

(920,)

In [57]:
y_pred = price_prediction.predict(X_test)

29/29 [==============================] - 0s 1ms/step


In [58]:
y_pred

array([[  50824.016 ],
       [   9939.762 ],
       [ 293897.12  ],
       [  18511.791 ],
       [  29453.2   ],
       [  30587.713 ],
       [  28363.783 ],
       [   9479.468 ],
       [   9048.757 ],
       [  60533.977 ],
       [  34896.535 ],
       [  16984.1   ],
       [  34518.934 ],
       [  29679.27  ],
       [  26721.354 ],
       [  30923.078 ],
       [  21504.967 ],
       [  25816.346 ],
       [  52962.676 ],
       [  21518.252 ],
       [  24822.36  ],
       [  55169.277 ],
       [  14443.128 ],
       [  27980.762 ],
       [ 310179.44  ],
       [  26476.822 ],
       [  24013.865 ],
       [  18437.568 ],
       [  40812.965 ],
       [  24382.791 ],
       [  23742.95  ],
       [  31485.61  ],
       [  22610.178 ],
       [  28262.818 ],
       [  27388.443 ],
       [  45572.836 ],
       [  21941.725 ],
       [  24997.396 ],
       [  95269.055 ],
       [ 107761.23  ],
       [  40421.785 ],
       [  46057.72  ],
       [   9273.115 ],
       [  1

In [59]:
price_prediction.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer2 (Dense)              (None, 6)                 78        
                                                                 
 layer3 (Dense)              (None, 24)                168       
                                                                 
 Output (Dense)              (None, 1)                 25        
                                                                 
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________


In [60]:
test = [[3.0, 1.50, 1340, 7912, 1.5, 0, 0, 3, 1340, 0, 1955, 2005]]
price_prediction.predict(test)

1/1 [==============================] - 0s 59ms/step


array([[27035.74]], dtype=float32)

In [62]:
price_prediction.evaluate(X_test, y_test)

29/29 [==============================] - 0s 1ms/step - loss: 487752.6875


487752.6875

In [63]:
type(price_prediction)

keras.engine.sequential.Sequential

In [64]:
price_prediction.weights

[<tf.Variable 'layer2/kernel:0' shape=(12, 6) dtype=float32, numpy=
 array([[ 3.0666524e-01, -4.9989828e-01, -6.8678044e-02, -2.1387851e-01,
          1.1993369e-01,  3.9881170e-01],
        [ 4.7567278e-01,  3.1370264e-01, -3.9702572e-02,  6.5884960e-01,
          1.7496482e-01,  5.7255912e-01],
        [ 4.9953040e-01,  4.9092188e-01,  3.1559047e-01,  6.8953180e-01,
          2.5774500e-01,  3.3602592e-02],
        [ 6.9585487e-02,  2.0408745e-01,  4.7699246e-01,  6.6876370e-01,
         -3.9683855e-01,  6.4670563e-01],
        [ 5.8931403e-02,  4.7147149e-01,  1.3678744e-01,  6.9687784e-01,
         -6.4564100e-04,  2.0528890e-01],
        [ 1.0190048e-01, -2.9774821e-01, -8.0211386e-02, -2.0202637e-01,
          3.4503600e-01,  1.6514459e-01],
        [-3.9420044e-01, -9.5732257e-02,  5.8768857e-01,  9.5698386e-02,
          1.3046135e-01,  4.5799541e-01],
        [ 2.9191679e-01, -1.9198155e-03, -3.1520286e-01,  3.7698835e-01,
         -3.8904530e-01,  2.4461865e-02],
        [ 3.